<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // users テーブル
        DB::table('users')->insert([
            'name' => 'Test User',
            'email' => 'gmail@gmail.com',
            'password' => Hash::make('password'),
            'telephone_number' => '09012345678',
            'post_code' => '123-4567',
            'prefectures' => 'Tokyo',
            'municipalities' => 'Shibuya',
            'street_address' => '1-2-3',
            'admin_flag' => false,
            'remember_token' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('tags')->insert([
            [
                'id' => 1,
                'value' => 'Beautyブレンド',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'value' => '季節の変わり目ブレンド',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' =>3,
                'value' => 'おやすみブレンド',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'value' => '体サポートブレンド',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'value' => '心ブレンド',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // product_details テーブル
        DB::table('product_details')->insert([
            [
                'id' => 1,
                'name' => 'Beautiful womanブレンド',
                'tag_id' => 1,
                'number' => 101,
                'type' => 'BLEND',
                'image_url' => '/101.png',
                'color' => true,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => '春も快適サポートブレンド',
                'tag_id' => 2,
                'number' => 102,
                'type' => 'BLEND',
                'image_url' => '/102.png',
                'color' => false,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'めぐりサポートブレンド',
                'tag_id' => 3,
                'number' => 103,
                'type' => 'BLEND',
                'image_url' => '/103.png',
                'color' => true,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => '疲れた筋肉サポートブレンド',
                'tag_id' => 2,
                'number' => 104,
                'type' => 'BLEND',
                'image_url' => '/104.png',
                'color' => false,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => '食後のおすすめブレンド',
                'tag_id' => 3,
                'number' => 109,
                'type' => 'BLEND',
                'image_url' => '/109.png',
                'color' => true,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => '気分を穏やかに過ごしたい時に',
                'tag_id' => 1,
                'number' => 110,
                'type' => 'BLEND',
                'image_url' => '/110.png',
                'color' => false,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'もしかして鉄分不足？と感じたときに',
                'tag_id' => 1,
                'number' => 111,
                'type' => 'BLEND',
                'image_url' => '/111.png',
                'color' => true,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => '頭リフレッシュブレンド',
                'tag_id' => 5,
                'number' => 112,
                'type' => 'BLEND',
                'image_url' => '/112.png',
                'color' => false,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => '健康維持に役立つブレンド',
                'tag_id' => 2,
                'number' => 118,
                'type' => 'BLEND',
                'image_url' => '/118.png',
                'color' => true,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => '心地よい香りで気分転換サポートブレンド',
                'tag_id' => 3,
                'number' => 119,
                'type' => 'BLEND',
                'image_url' => '/119.png',
                'color' => false,
                'price' => 600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            
        ]);

        // amounts テーブル
        DB::table('amounts')->insert([
            ['value' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['value' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['value' => 30, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // product_prices テーブル
        DB::table('product_prices')->insert([
            ['amount_id' => 1, 'price' => 600,  'created_at' => now(), 'updated_at' => now()],
            ['amount_id' => 2, 'price' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['amount_id' => 3, 'price' => 1500, 'created_at' => now(), 'updated_at' => now()],
        ]);
        DB::table('products')->insert([
            ['product_detail_id' => 1, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'product_price_id' => 1,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'product_price_id' => 2,  'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'product_price_id' => 3,  'created_at' => now(), 'updated_at' => now()],
            
        ]);

        // ingredients テーブル
        DB::table('ingredients')->insert([
            ['value' => 'レモンバーム', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'レモングラス', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ペパーミント', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ローズヒップ', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'オレンジピール', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'リンデンフラワー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ジャーマンカモミール', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'マルベリー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ラベンダー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'パッションフラワー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ネトル', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ローズマリー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'カレンデュラ', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'フィーバーフュー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ラズベリーリーフ', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ヒース', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ローズレッド', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'エルダーフラワー', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'エキナセア', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ルイボス', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'セントジョーンズワート', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ダンディライオン', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ハイビスカス', 'created_at' => now(), 'updated_at' => now()],
            ['value' => 'ジンジャー', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // ingredient_product_details 中間テーブル
        DB::table('ingredient_product_details')->insert([
            ['product_detail_id' => 1, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'ingredient_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'ingredient_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'ingredient_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'ingredient_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'ingredient_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'ingredient_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'ingredient_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'ingredient_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'ingredient_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'ingredient_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'ingredient_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'ingredient_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'ingredient_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'ingredient_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'ingredient_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'ingredient_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'ingredient_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'ingredient_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'ingredient_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'ingredient_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'ingredient_id' => 18, 'created_at' => now(), 'updated_at' => now()],
        ]);

        // comments テーブル
        DB::table('comments')->insert([
            ['product_detail_id' => 1, 'value' => '毎日の美容習慣に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'value' => '内側から輝くように毎日をサポート', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 1, 'value' => '美肌のサポートに', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'value' => '気持ちよく春を迎えたい', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'value' => '季節の変わり目にホッと一息', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 2, 'value' => 'ペパーミントのさわやかな香りで気分をすっきりさせたい時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'value' => '冷えを感じる時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'value' => 'ぬくもり薫ハーブブレンド', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 3, 'value' => '身体を温めうブレンド', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'value' => 'スポーツ後のリフレッシュに', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'value' => '身体をやすめたい時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'value' => '頑張った一日の終わりに', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 4, 'value' => '肩、腰', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'value' => '胃腸を労りたい時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'value' => '重たい食事の後におすすめ', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 9, 'value' => '食後をすっきりさせてくれるハーブティー', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'value' => '忙しい日々に心安らぐひと時を', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 10, 'value' => '健康な生活習慣をサポート', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'value' => 'デスクワークの合間の気分転換に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 11, 'value' => '循環をサポート', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'value' => '頭をすっきりさせたい時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'value' => '頭が重たいと感じた時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 12, 'value' => '気分をやわらげたい時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'value' => '季節の変わり目に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'value' => '体調を気にする時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 18, 'value' => '健康管理のために', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'value' => '胃腸を労りたい時に', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'value' => '重たい食事の後におすすめ', 'created_at' => now(), 'updated_at' => now()],
            ['product_detail_id' => 19, 'value' => '食後をすっきりさせてくれるハーブティー', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // favorites テーブル
        DB::table('favorites')->insert([
            [
                'user_id' => 1,
                'product_detail_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
