services:
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www/html
    depends_on:
      - db

  web:
    build:
      context: ./back/nginx
    ports:
      - "8006:80"
    volumes:
      - ./back:/var/www/html
      - ./back/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: magokoro-herb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  front:
    build: ./front
    volumes:
      - ./front:/front
      - front_node_modules:/front/node_modules
    ports:
      - "3006:3000"
    depends_on:
      - web

volumes:
  db_data:
  front_node_modules:
