import type { Metadata } from "next";
import { Mochiy_Pop_One } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";

const mochiyPopOne = Mochiy_Pop_One({
  variable: "--font-mochiy-pop-one", // グローバルCSS変数として利用可能
  subsets: ["latin"],                // ラテン文字のグリフのみを読み込む
  weight: "400",                     // ウェイト400（レギュラー）
  display: "swap",                   // フォントの表示方式（SWAP推奨）
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mochiyPopOne.className} antialiased bg-bg text-text`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
